# Generated by Django 4.1.4 on 2023-03-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QACModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Policy_Number', models.CharField(max_length=12)),
                ('Case_Number', models.CharField(max_length=7)),
                ('AVS_Check', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAUL'), ('UNVERIFIED', 'UNVERIFIED')], max_length=12)),
                ('Caller_ID', models.CharField(max_length=50)),
                ('Sales_Agent', models.CharField(max_length=50)),
                ('Call_duration', models.CharField(max_length=10)),
                ('Start_date', models.CharField(max_length=20)),
                ('Premium', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Debit_date', models.CharField(max_length=10)),
                ('Cover_amount', models.CharField(max_length=10)),
                ('QA_Correct', models.CharField(choices=[('FALSE', 'FALSE'), ('TRUE', 'TRUE')], max_length=5)),
                ('KPA_Outcome', models.CharField(max_length=15)),
                ('HIV_Required', models.CharField(max_length=3)),
            ],
        ),
    ]
