# Generated by Django 4.1.4 on 2023-03-19 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SouthsideApp', '0003_qacmodels_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='QACAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='qacmodels',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qacmodels',
            name='AVS_Check',
            field=models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL'), ('UNVERIFIED', 'UNVERIFIED')], max_length=12),
        ),
    ]
