# Generated by Django 4.1.4 on 2023-03-19 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SouthsideApp', '0005_rename_qacagent_qaagent_qacmodels_qa_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qacmodels',
            name='user',
        ),
    ]
