# Generated by Django 4.1.4 on 2023-03-20 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SouthsideApp', '0007_remove_qacmodels_qa_agent_qacmodels_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qacmodels',
            name='user',
        ),
        migrations.AddField(
            model_name='qacmodels',
            name='QA_Agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SouthsideApp.qaagent'),
        ),
    ]
