# Generated by Django 4.1.4 on 2023-03-23 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SouthsideApp', '0009_qaagent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qacmodels',
            name='QA_Agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='QAAgent',
        ),
    ]
